spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart-market
    username: root
    password: "@Senha01*"
    driver-class-name: com.mysql.cj.jdbc.Driver  

server:
  port: 8080
  servlet:
    context-path: /smart-market